[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fast_factorial"
version = "0.1.0"
description = "Fast factorial calculation using C"
authors = [
    { name = "Visitha", email = "visitha2001@gmail.com" }
]
requires-python = ">=3.10"